version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
    - db
    environment:
    - DB_URL=mongodb://db:27017/urls
  db:
    ports:
      - "27017:27017"
    image: mongo
